version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "your_db_user"]
      interval: 5s
      retries: 5

  api:
    build: .
    container_name: fastapi_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app_network


volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
