name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set environment variables
      run: |
        echo "DB_HOST=db" >> $GITHUB_ENV
        echo "DB_USER=your_db_user" >> $GITHUB_ENV
        echo "DB_PASSWORD=your_db_password" >> $GITHUB_ENV
        echo "DB_NAME=your_db_name" >> $GITHUB_ENV

    - name: Start containers
      run: docker compose -f "docker-compose.yml" up -d --build

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yml" down