name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create .env file
      run: |
        echo "POSTGRES_DB=your_db_name" > .env
        echo "POSTGRES_USER=your_db_user" >> .env
        echo "POSTGRES_PASSWORD=your_db_password" >> .env
        echo "DB_HOST=db" >> .env
        echo "DB_PORT=5432" >> .env

    - name: Start containers
      run: docker compose -f "docker-compose.yml" up -d --build

    - name: Debug environment variables
      run: docker exec fastapi_app env

    - name: Wait for PostgreSQL
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        until docker exec fastapi_app pg_isready -h db -p 5432 -U your_db_user; do
          sleep 2
        done

    - name: Run migrations
      run: docker exec fastapi_app alembic upgrade head

    - name: Check database logs
      if: failure()
      run: docker logs db

    - name: Run tests with coverage
      run: |
        docker exec fastapi_app pytest --cov=app --cov-fail-under=95 tests/

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yml" down