name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov

    - name: Build the docker-compose stack
      run: docker-compose up -d

    - name: Check running containers
      run: docker ps

    - name: Set up environment variables for database
      run: |
        echo "POSTGRES_DB=your_db_name" >> $GITHUB_ENV
        echo "POSTGRES_USER=your_user" >> $GITHUB_ENV
        echo "POSTGRES_PASSWORD=your_password" >> $GITHUB_ENV
        echo "DB_HOST=db" >> $GITHUB_ENV
        echo "DB_PORT=5432" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Wait for database to be ready
      run: |
        until docker-compose exec app nc -z db 5432; do
          echo "Waiting for database..."
          sleep 1
        done

    - name: Run migrations
      run: |
        docker-compose exec app alembic upgrade head

    - name: Run tests with coverage
      run: |
        pytest --cov=app --cov-fail-under=95 tests/

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
