name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create .env file
      run: |
        echo "DB_HOST=your_db_host" > .env
        echo "DB_USER=your_db_user" >> .env
        echo "DB_PASSWORD=your_db_password" >> .env
        echo "DB_NAME=your_db_name" >> .env

    - name: Start containers
      run: docker compose -f "docker-compose.yml" up -d --build

    - name: Run migrations
      run: |
        docker exec fastapi_app alembic upgrade head

    - name: Run tests with coverage
      run: |
        docker exec fastapi_app pytest --cov=app --cov-fail-under=95 tests/

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yml" down